In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn
import librosa
import librosa.display
import IPython.display as ipd 

In [6]:
import sklearn as sk
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [13]:
file_name = "E:/Projects/factory_noises/-6_dB_fan/fan/id_00/abnormal/00000000.wav"

In [14]:
def extract_feature(file_name):
    X, sample_rate = librosa.load(file_name)

    # sftf
    stft = np.abs(librosa.stft(X))

    # mfcc
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)

    # chroma
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)

    # melspectrogram
    mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)

    # spectral contrast
    contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)

    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X), sr=sample_rate).T,axis=0)
    
    return mfccs,chroma,mel,contrast,tonnetz

In [15]:
extract_feature(file_name)

(array([-364.5717   ,  166.06549  ,  -33.734016 ,   54.899452 ,
         -37.32164  ,   38.491657 ,  -22.788269 ,   32.459522 ,
          -0.7616068,    1.096578 ,   -1.9819955,    1.9596686,
           7.131522 ,   -3.7504678,   22.208961 ,   -6.2551794,
          13.383363 ,  -11.525628 ,    5.370641 ,   -2.8982475,
           0.7855515,    7.5751686,   -8.302987 ,   -1.015255 ,
          -9.16558  ,    1.9314033,   -5.5575066,    8.585413 ,
           2.479782 ,    4.346129 ,   -6.6728425,   -7.202294 ,
           2.0274394,    1.3539858,    7.414005 ,   -3.0526466,
          -0.6495085,  -12.275102 ,   -2.6267314,   -3.5094275],
       dtype=float32),
 array([0.5934977 , 0.52214664, 0.65450674, 0.64531225, 0.45443103,
        0.43772778, 0.5164612 , 0.45712885, 0.5967617 , 0.59716886,
        0.70899177, 0.99653405], dtype=float32),
 array([7.53737018e-02, 9.36119854e-01, 1.08929658e+00, 9.34863985e-02,
        3.10630351e-01, 2.29058251e-01, 5.32274544e-02, 6.30522072e-02,
       